###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
#    memcached:
#        image: 'memcached:alpine'

    redis:
        image: 'redis:alpine'

    pollux-postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/db_data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_USER=pollux_admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=dbpollux
        ports:
            - '21004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
